FROM python:3.12-slim

WORKDIR /app

RUN pip install poetry uv
RUN poetry self add poetry-plugin-export

COPY pyproject.toml .
COPY poetry.lock .

RUN poetry export --without-hashes > ./requirements.txt
RUN uv pip install --system -r requirements.txt

COPY *.py /app/
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

CMD ["/app/entrypoint.sh", "fetch"]
